# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileWidget.ui'
#
# Created: Mon Feb 16 00:59:20 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FileWidget(object):
    def setupUi(self, FileWidget):
        FileWidget.setObjectName("FileWidget")
        FileWidget.resize(852, 426)
        self.verticalLayout = QtGui.QVBoxLayout(FileWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(FileWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newTab = QtGui.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/media/file/new_tab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newTab.setIcon(icon)
        self.newTab.setIconSize(QtCore.QSize(24, 24))
        self.newTab.setObjectName("newTab")
        self.horizontalLayout_2.addWidget(self.newTab)
        self.back = QtGui.QPushButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ui/media/file/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon1)
        self.back.setIconSize(QtCore.QSize(24, 24))
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.next = QtGui.QPushButton(self.layoutWidget)
        self.next.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ui/media/file/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon2)
        self.next.setIconSize(QtCore.QSize(24, 24))
        self.next.setObjectName("next")
        self.horizontalLayout_2.addWidget(self.next)
        self.up = QtGui.QPushButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ui/media/file/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up.setIcon(icon3)
        self.up.setIconSize(QtCore.QSize(24, 24))
        self.up.setObjectName("up")
        self.horizontalLayout_2.addWidget(self.up)
        self.home = QtGui.QPushButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ui/media/file/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon4)
        self.home.setIconSize(QtCore.QSize(24, 24))
        self.home.setObjectName("home")
        self.horizontalLayout_2.addWidget(self.home)
        self.url = QtGui.QLineEdit(self.layoutWidget)
        self.url.setObjectName("url")
        self.horizontalLayout_2.addWidget(self.url)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save = QtGui.QPushButton(self.layoutWidget1)
        self.save.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ui/media/file/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save.setIcon(icon5)
        self.save.setIconSize(QtCore.QSize(24, 24))
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.saveas = QtGui.QPushButton(self.layoutWidget1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ui/media/file/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveas.setIcon(icon6)
        self.saveas.setIconSize(QtCore.QSize(24, 24))
        self.saveas.setObjectName("saveas")
        self.horizontalLayout.addWidget(self.saveas)
        self.undo = QtGui.QPushButton(self.layoutWidget1)
        self.undo.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ui/media/file/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo.setIcon(icon7)
        self.undo.setIconSize(QtCore.QSize(24, 23))
        self.undo.setObjectName("undo")
        self.horizontalLayout.addWidget(self.undo)
        self.redo = QtGui.QPushButton(self.layoutWidget1)
        self.redo.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ui/media/file/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redo.setIcon(icon8)
        self.redo.setIconSize(QtCore.QSize(24, 24))
        self.redo.setCheckable(False)
        self.redo.setObjectName("redo")
        self.horizontalLayout.addWidget(self.redo)
        self.find = QtGui.QPushButton(self.layoutWidget1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/ui/media/file/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find.setIcon(icon9)
        self.find.setIconSize(QtCore.QSize(24, 24))
        self.find.setObjectName("find")
        self.horizontalLayout.addWidget(self.find)
        self.detach = QtGui.QPushButton(self.layoutWidget1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/ui/media/file/detach.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detach.setIcon(icon10)
        self.detach.setIconSize(QtCore.QSize(24, 24))
        self.detach.setObjectName("detach")
        self.horizontalLayout.addWidget(self.detach)
        self.close = QtGui.QPushButton(self.layoutWidget1)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/ui/media/file/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon11)
        self.close.setIconSize(QtCore.QSize(24, 24))
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.verticalLayout.addWidget(self.splitter)
        self.editor = Qsci.QsciScintilla(FileWidget)
        self.editor.setObjectName("editor")
        self.verticalLayout.addWidget(self.editor)

        self.retranslateUi(FileWidget)
        QtCore.QMetaObject.connectSlotsByName(FileWidget)

    def retranslateUi(self, FileWidget):
        FileWidget.setWindowTitle(QtGui.QApplication.translate("FileWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.newTab.setToolTip(QtGui.QApplication.translate("FileWidget", "New Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setToolTip(QtGui.QApplication.translate("FileWidget", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.next.setToolTip(QtGui.QApplication.translate("FileWidget", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.up.setToolTip(QtGui.QApplication.translate("FileWidget", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.home.setToolTip(QtGui.QApplication.translate("FileWidget", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setToolTip(QtGui.QApplication.translate("FileWidget", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveas.setToolTip(QtGui.QApplication.translate("FileWidget", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.undo.setToolTip(QtGui.QApplication.translate("FileWidget", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.redo.setToolTip(QtGui.QApplication.translate("FileWidget", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.find.setToolTip(QtGui.QApplication.translate("FileWidget", "Find / Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.detach.setToolTip(QtGui.QApplication.translate("FileWidget", "Detach", None, QtGui.QApplication.UnicodeUTF8))
        self.close.setToolTip(QtGui.QApplication.translate("FileWidget", "Close", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qsci
import resources_rc
